Revert "adding ##'  @rdname omxLogical tag to omxNot. Does it fix the no-rd file CRAN error for this function?"
This reverts commit 0bdf1d1a2e4f094478fd5ffc4fa00383a3450ff0.

R 3.1.1 complains with

** help
Error : /sfs/gluster/bigtmp/jnp3bc/23222/build/man/omxLogical.Rd: Sections \title, and \name must exist and be unique in Rd files
ERROR: installing Rd objects failed for package ‘OpenMx’