added info to starting values conflict to help the user respond effectively
e.g.
bothSexes1 = mxRun(bothSexes1)
Running Both 
Error: The free parameter 'PaternalSESfac_HousingTenure7fac' has been assigned multiple starting values! See matrix 'girl1.S' at location (2, 1) and matrix 'boy1.S' at location (2, 1) If you want to fix this automatically, call model <- omxAssignFirstParameters(model) before running again
 


git-svn-id: http://openmx.psyc.virginia.edu/svn/trunk@2068 df83fd30-4cca-4c36-ab9d-e8b5583ccbd1