Updated checkNamespaceHelper(model, topmodel, namespace)
* Following on from  http://openmx.psyc.virginia.edu/thread/735, updated error message to be more like a highway barrier.
* Fixed side-effect in "NameParameterOverlap.R" so that it now checks for the new-style error

Now reads:
mxRun(model)
Error: In model 'model' the following are both named entities and free parameters: 'foo' 
If you are trying to set a path using an mxAlgebra, then refer to the Algebra with square-bracket notation. 
i.,e, instead of labels=" 'foo' " use: labels=" 'foo' [1,1]"



git-svn-id: http://openmx.psyc.virginia.edu/svn/trunk@2363 df83fd30-4cca-4c36-ab9d-e8b5583ccbd1